### ISSUE TITLE
Consumer keys

### ISSUE THREAD

**Issue by iblancasa** [juanvelascogomez/harvey#2]
En vez de tener que modificar el fichero [secrets.py](https://github.com/juanvelascogomez/harvey/blob/master/Claves/secrets.py) para insertar las claves, es una práctica recomendada utilizar variables de entorno: es más práctico y no habrá problemas con Git por haber modificado el fichero

**Comment by juanvelascogomez** [comment]
Gracias por el aviso @iblancasa , en cuanto pueda ponerme de nuevo con el código lo corregiré.

**Comment by juanvelascogomez** [comment]
Dejo abierto el issue hasta que quede hecho.
